import fs from 'fs';

const rows = [
  ["Feature/Capability", "Claimed in Docs (quote source)", "DB Schema Support (migration file + table/function)", "Server Implementation (file + lines or NONE)", "Test Coverage (test file + pass/fail)", "Railway Deployable (YES/NO + blockers)", "External Dependencies Required", "Effort to Close (hours/days/weeks)", "Can Close Without External Deps (YES/NO)"],
  ["Campaigns CRUD", "README: \"businesses fund campaigns\"; STATUS: \"campaigns, tasks, payouts, disputes, admin, verification workers\" in amplo output", "0001_core.sql: campaigns table (id, owner_id, title, brief, platform, objective, state, budget_minor, spent_minor, currency, price_per_outcome_minor, promoter_share_bp, fraud_reserve_bp, margin_floor_bp, hold_hours, auto_pause_pct, starts_at, ends_at); triggers: assert_campaign_funded, apply_campaign_autopause, assert_campaign_margin_floor", "NONE — no API routes for campaigns in server.mjs or app.js; index.html has \"Fund a campaign\" CTA but no backend", "ledger.test.mjs: 56 PASS / 0 FAIL / 2 UNVERIFIED (campaign guards, escrow, auto-pause proven at DB level); RLS policies untested locally", "NO — no API layer; would need campaign API endpoints + admin UI", "Supabase (PostgREST)", "weeks (API + UI + auth integration)", "YES (can build API on existing DB)"],
  ["Task State Machine", "README: \"verified Nigerians promote... earn mobile data first, cash as they grow — for checked results only\"; LEAD-CAPTURE: \"24h auto-approve... task state machine with 24h auto-approve\"", "0001_core.sql: tasks table (id, campaign_id, state, caption, tracked_link, disclosure_tag, reward_minor, assigned_to, assigned_at, submitted_at, proof_url, auto_approve_at, hold_until, reviewed_by, rejection_reason); triggers: assert_task_transition, auto_approve_stale_tasks; outbox event task.auto_approved", "NONE — no task API or promoter dashboard in server.mjs/app.js", "ledger.test.mjs: 56 PASS / 0 FAIL / 2 UNVERIFIED (task transitions, auto-approve proven at DB level)", "NO — no API layer; would need task API + promoter dashboard + assignment logic", "Supabase", "weeks (API + dashboard + assignment worker)", "YES (DB logic complete)"],
  ["Payouts / Ledger", "README: \"earn mobile data first, cash as they grow\"; LEAD-CAPTURE: \"cash flows only from verified work\"; BRAND: \"Data before cash MTN, Glo and Airtel bundles\"", "0001_core.sql: accounts, ledger_entries, postings (double-entry, deferred balance constraint, single-currency, immutable); payouts table (kind: data/airtime/cash/giftcard, amount_minor, currency, status, provider_ref, idempotency_key, hold_until); triggers: assert_payout_eligibility (cash requires KYC t2 + age_verified; data/airtime requires verified phone); outbox table + claim_outbox_batch; settings for payout thresholds", "server.mjs: NONE (static server only); apps/web/app.js: NONE (lead capture only)", "ledger.test.mjs: 56 PASS / 0 FAIL / 2 UNVERIFIED (balance, immutability, idempotency, campaign guards, escrow, auto-pause, payout eligibility, roles, disputes, settings, global sweeps, outbox claim, reversal — ALL HOLD at DB level)", "NO — no payout execution worker, no provider integration, no KYC/IDV flow", "Termii (SMS), Payment gateway (Flutterwave/Paystack), KYC provider (Smile Identity/VerifyMe)", "weeks (payout worker + provider integrations + KYC flow + admin approval UI)", "NO (requires external payment + KYC providers)"],
  ["Disputes", "LEAD-CAPTURE: \"Attribution disputes: code + timestamp + UTM stored per lead; outbox event per capture\"; STATUS: \"dispute lifecycle\"", "0001_core.sql: disputes table (id, task_id, raised_by, reason, state, resolution, sla_due_at, resolved_by, resolved_at); trigger: assert_dispute_transition (open->under_review->upheld/rejected/withdrawn/expired; decision requires named reviewer)", "NONE — no dispute API or UI", "ledger.test.mjs: 56 PASS / 0 FAIL / 2 UNVERIFIED (dispute transitions proven at DB level)", "NO — no API/UI", "Supabase", "days (API + promoter dashboard + admin review UI)", "YES (DB logic complete)"],
  ["Admin / Roles / Settings", "STATUS: \"RBAC with trigger-guarded roles, typed settings, append-only audit\"; BRAND: \"admin/roles/settings UI 0%\"", "0001_core.sql: profiles (role, state, kyc_tier, trust_score); permissions, role_permissions, user_permissions; assign_role() with guard_role_change trigger; settings table (typed, versioned, admin-only writes); audit_log (append-only); RLS policies for all", "server.mjs: NONE; apps/web/app.js: NONE (no admin area)", "ledger.test.mjs: 56 PASS / 0 FAIL / 2 UNVERIFIED (role change guard, suspension, settings guards proven at DB; assign_role success path UNVERIFIED — needs real JWT)", "NO — no admin API/UI", "Supabase", "weeks (admin API + full admin dashboard + role management UI)", "YES (DB logic complete)"],
  ["Verification Workers (SMS/Termii)", "LEAD-CAPTURE: \"SMS worker consumes outbox -> Termii OTP -> verified_at\"; \"SMS double opt-in (Termii) designed (outbox lead.captured is the handoff); no key, no worker\"; STATUS blocker #5: \"Termii API key for the SMS double opt-in worker\"", "0002_leads.sql: leads table has verified_at; trigger notify_lead_captured emits outbox topic lead.captured with lead_id, lane, phone; 0003_access_control.sql: prune_unverified_leads function (service_role only)", "server.mjs: NONE; apps/web/app.js: NONE (form shows \"verified_at flows later\")", "leads.test.mjs: 37 PASS / 0 FAIL / 1 UNVERIFIED (outbox event emission proven); live.proof.mjs: PASS 14/0/0 (outbox event verified live)", "NO — no worker process deployed; Termii API key missing", "Termii API key (SMS/WhatsApp OTP)", "days (worker + Termii integration + deploy)", "NO (requires Termii API key)"],
  ["KYC / IDV (Identity Verification)", "BRAND: \"Cash needs identity checks, a minimum balance and a batched payout schedule\"; STATUS: \"Registered entity name/jurisdiction + PII-storage decision\" blocker; LEAD-CAPTURE: \"Swagbucks IDV: Constraints disclosed at setup, never discovered at payout\"", "0001_core.sql: profiles has kyc_tier (t0/t1/t2), age_verified_at, date_of_birth_hmac, identity_ref (provider token OR HMAC(NIN/BVN)); payouts trigger assert_payout_eligibility requires KYC t2 + age_verified for cash", "NONE — no KYC flow in server.mjs/app.js", "ledger.test.mjs: payout eligibility tests PASS (cash requires t2+age, data requires verified phone) — but KYC tier assignment path UNVERIFIED", "KYC provider (Smile Identity, VerifyMe, Youverify), NIN/BVN verification", "weeks (KYC integration + consent flow + document upload + review queue)", "NO (requires KYC provider)"],
  ["Payment Gateway", "BRAND: \"Withdrawal rules: Data rewards go only to your own verified numbers. Cash needs identity checks, a minimum balance and a batched payout schedule\"; LEAD-CAPTURE: \"cash flows only from verified work\"", "0001_core.sql: payouts table supports kind=cash; ledger has PLATFORM_CASH_NGN/USD accounts; settings: payout.min_cash_minor, payout.min_data_minor, payout.hold_hours, payout.batch_size", "NONE — no payment gateway integration", "ledger.test.mjs: payout eligibility proven at DB; no integration tests", "Payment gateway (Flutterwave, Paystack, Monnify) for NGN payouts; data aggregator (Termii, Migo, etc.) for airtime/data", "weeks (gateway integration + webhook handling + reconciliation + compliance)", "NO (requires payment gateway)"],
  ["Platform OAuth (YouTube/Facebook/Twitter)", "index.html: \"Connect YouTube or Facebook so we can confirm the post is really yours. Minimum 200 followers at pilot.\"", "0001_core.sql: profiles has no OAuth token fields; tasks has tracked_link but no platform credential storage", "NONE — no OAuth flow", "no tests", "OAuth providers (Google/YouTube, Meta/Facebook, Twitter/X)", "weeks (OAuth flows + token storage + platform API verification + follower count check)", "NO (requires OAuth providers)"],
  ["Rate Limiting / Abuse Controls", "LEAD-CAPTURE: \"Abuse controls in a trigger (fire for every role) AND in RLS (access layer): honeypot empty, consent within the last 30 minutes and never future, phone shape\"; \"Bot form fills: honeypot + consent freshness, trigger + RLS\"", "0002_leads.sql: assert_lead_validity trigger (honeypot, consent freshness, phone format); RLS policy leads_anon_insert enforces same; UNIQUE(phone) prevents duplicate signups; 0004/0007 submit_lead: honeypot, consent, phone validation, duplicate check with indistinguishability", "server.mjs: no rate limiting (no middleware); apps/web/app.js: client-side validation only (honeypot empty, phone format, consent timestamp)", "leads.test.mjs: 37 PASS / 0 FAIL / 1 UNVERIFIED (honeypot, consent, phone, duplicate, referral code format, self-referral, unknown ref all proven at DB); phone.test.mjs: 17 PASS (phone normalization)", "NO — rate limiting at edge/CDN or application layer missing", "Supabase (PostgREST has some built-in)", "days (edge rate limit via Railway/Cloudflare + application-level)", "YES (can add Railway/Cloudflare rate limiting)"],
  ["Observability / Logging", "STATUS: \"append-only audit\"; server.mjs: console.log only", "0001_core.sql: audit_log table (actor_id, actor_role, action, target_type, target_id, before_state, after_state, ip, user_agent, created_at); trigger forbid_audit_mutation", "server.mjs: minimal console.log (startup, errors); no structured logging, no metrics, no tracing", "ledger.test.mjs: audit_log append proven; no observability tests", "NO — no logging infrastructure, no metrics, no alerting", "Logging provider (Datadog, Grafana Cloud, Axiom)", "days (structured logging + metrics + alerting)", "YES (can self-host or use free tiers)"],
  ["CI/CD Pipeline", "STATUS: \"amplo build (8 commits, gate 41/0/0 GREEN)\"; \"GitHub remote pushed and verified\"; \"Railway deploy verified\"", "migrateRemote.mjs: advisory lock, checksum validation, drift detection, per-migration transactions", "ledger.test.mjs + leads.test.mjs + phone.test.mjs + lead.test.mjs run via npm test; checkSite.mjs for static integrity", "YES — deployed and verified (PROOF/C3-railway-live/); Railway auto-deploys on push", "GitHub Actions (not configured — manual push/deploy)", "hours (add GitHub Actions workflow)", "YES (GitHub Actions free)"],
  ["RLS Policies", "STATUS: \"RLS policies are deployed but UNPROVEN — staging with real JWTs required\"; \"RLS policies verified over HTTP by db/live.proof.mjs\"; LEAD-CAPTURE: \"RLS anon matrix proof over HTTP DONE — db/live.proof.mjs PASS 14/0/0\"", "0001_core.sql: RLS enabled on all tables; policies for profiles, campaigns, tasks, payouts, settings, disputes, audit_log; functions current_role_name(), has_perm(); 0002_leads.sql: leads_anon_insert policy (INSERT only, with consent/honeypot/phone checks); 0003_access_control.sql: explicit GRANT/REVOKE for anon/authenticated/service_role; 0006_secure_migration_ledger.sql: migration ledger RLS enabled", "server.mjs: serves config.js with anon key; apps/web/app.js: calls submit_lead RPC with anon key", "live.proof.mjs: PASS 14 / FAIL 0 / UNVERIFIED 0 — ALL HOLD over real HTTPS with anon JWT (visitor submit, no read, no update, no delete, no ledger read, duplicate refused, signed-in blocked from leads, can read campaigns, row+outbox exist, cleanup works)", "YES — proven live", "Supabase (PostgREST RLS)", "N/A (already deployed and proven)", "N/A"],
  ["Legal Pages (Terms/Privacy/Refund)", "index.html footer: \"Terms, privacy policy and refund policy are published before the pilot opens.\"", "NONE", "NONE", "no tests", "NO — pages dont exist", "Legal counsel", "days (draft + review + publish)", "YES (can draft internally)"],
  ["Lead Capture (submit_lead)", "LEAD-CAPTURE: \"visitor -> validated form -> honeypot + consent timestamp -> POST /rest/v1/rpc/submit_lead -> returns ONLY { referral_code, position, referred } — no personal data\"; \"One public write action, not a writable table\"", "0002_leads.sql: leads table; 0004_submit_lead.sql + 0007_fix_submit_lead_oracle.sql: submit_lead RPC (validates consent, honeypot, phone, name, duplicate check with indistinguishability, inserts lead, assigns code, emits outbox, returns code/position/referred); normalise_nigerian_phone", "server.mjs: serves /config.js with SUPABASE_URL + ANON_KEY; apps/web/app.js: buildLeadPayload, buildSubmitArgs, submitLead (fetch to RPC), rpcPosition, rpcPreview, invite resolution", "lead.test.mjs: 17 PASS (ref parsing, code format, UTM, payload, submit args, share links); leads.test.mjs: 37 PASS / 0 FAIL / 1 UNVERIFIED (submit_lead RPC proven); live.proof.mjs: PASS 14/0/0 (end-to-end live)", "YES — deployed and proven live", "Supabase (PostgREST)", "N/A (complete)", "N/A"],
  ["Referral Growth Engine", "LEAD-CAPTURE: \"Every captured lead becomes a distributor: personal link -> WhatsApp/X/Facebook intents... invitee lands with ?ref= -> banner names inviter (masked) -> position counter... Referrals pay ZERO. Queue priority only\"", "0002_leads.sql: leads.referred_by_code FK to leads.referral_code; assign_referral_code trigger (8-char unambiguous alphabet, collision retry); preview_referral RPC (masked referrer name); lead_position RPC (queue position + referred count); outbox event lead.captured", "apps/web/app.js: getRefFromLocation, isReferralCodeFormat, shareLinks, showReferral (displays code, position, referred count, share intents)", "lead.test.mjs: referral code format, share links, payload/ref/UTM mapping PASS; leads.test.mjs: referral resolution, preview_referral masking, lead_position, 40-code regression guard PASS", "YES — deployed and proven live", "Supabase (PostgREST)", "N/A (complete)", "N/A"],
  ["Brand / Design System", "BRAND.md: \"Palette — every pair measured 2026-10-02 (WCAG 2.2 AA)\"; \"Typography: zero-dependency system stack\"; \"Logo and identity\"; \"Voice: clarity, customer language, specificity, honest, inversion, Pidgin seasoning\"", "brand.yaml (manifest); apps/web/assets/identity/* (SVG masters, PNG exports, DESIGN_BRIEF.json); apps/web/styles.css (CSS custom properties for all palette tokens)", "apps/web/theme-boot.js: no-flash theme boot; apps/web/app.js: theme toggle with localStorage + OS preference + aria; index.html: theme-aware picture banner", "theme-boot.js + app.js + checkSite.mjs verify theme toggle, color-scheme, reduced-motion, alt text, WCAG 2.2 AA", "YES — deployed", "None", "days (maintenance)", "YES"],
  ["SEO / noindex", "README: \"noindex stays until the SEO-D1 removal trigger is met (see amplo docs/SEO.md)\"; STATUS: \"Pre-launch noindex per SEO-D1\"", "index.html: <meta name=\"robots\" content=\"noindex,nofollow\">", "NONE", "checkSite.mjs: verifies meta tags, title, description, lang, viewport", "YES — deployed as intended", "None", "N/A (intentional)", "YES"],
  ["Static Site Integrity", "README: \"npm run site # page integrity: anchors, assets, SEO basics, theme switch, a11y tokens\"", "NONE", "server.mjs: serves static files with CSP, security headers; serve.mjs: loopback preview", "checkSite.mjs: PASS (anchors, assets, SEO basics, theme toggle, a11y tokens, reduced-motion, no dummy phones, no unsanctioned testimonials)", "YES — deployed", "None", "N/A (complete)", "YES"],
  ["Database Migration System", "STATUS: \"All seven migrations execute on real PostgreSQL\"; \"All six migrations 0001-0006 are applied live\"; migrateRemote.mjs safety properties", "migrations.mjs: orderedMigrations (local stubs + production); checksum verification", "migrateUp.mjs: PGlite local engine (real PostgreSQL WASM); migrateRemote.mjs: Supabase session pooler, advisory lock, ledger with checksum, drift detection, per-migration transactions", "ledger.test.mjs + leads.test.mjs run against PGlite; migrateUp.mjs: 7 APPLIED", "YES — deployed and proven", "Supabase (session pooler for DDL)", "N/A (complete)", "N/A"],
  ["Edge / CDN / TLS", "Railway provides TLS, custom domains not yet configured", "railway.json: healthcheckPath /healthz; Dockerfile: node:22-alpine", "server.mjs: CSP (connect-src self https://*.supabase.co), security headers (nosniff, frame-deny, referrer-policy, permissions-policy)", "verifyLive.mjs: PASS 19/0 (static assets, CSP, headers, runtime config, real sign-up)", "YES — Railway provides", "None (Railway included)", "N/A (complete)", "N/A"],
  ["Webhooks / Event Ingestion", "LEAD-CAPTURE: outbox pattern for async workers; STATUS: \"outbox event per capture\"", "0001_core.sql: outbox table + claim_outbox_batch (SKIP LOCKED); 0002_leads.sql: notify_lead_captured trigger emits lead.captured", "server.mjs: NONE (no webhook receiver)", "ledger.test.mjs: outbox claim proven; leads.test.mjs: outbox event emission proven", "NO — no webhook endpoint for provider callbacks (payment, SMS delivery)", "Provider webhooks (Termii, payment gateway)", "days (webhook endpoints + signature verification + idempotency)", "YES (can build on existing outbox)"],
  ["Email / Transactional Email", "Not claimed (privacy-first)", "NONE", "NONE", "no tests", "N/A", "Email provider (SendGrid, Resend, Postmark)", "days", "NO (requires provider)"],
  ["Analytics / Telemetry", "Not claimed (privacy-first)", "NONE", "NONE", "no tests", "N/A", "Analytics provider (Plausible, PostHog, self-hosted)", "days", "YES (can self-host)"],
  ["Internationalization (i18n)", "Not claimed (Nigeria pilot only)", "NONE", "NONE", "no tests", "N/A", "Translation files + i18n library", "weeks", "YES"],
  ["Mobile App (React Native/Flutter)", "Not claimed", "web only", "web only", "no tests", "N/A", "Mobile framework", "months", "NO"],
  ["Admin Dashboard", "STATUS: \"admin/roles/settings UI 0%\"", "0001_core.sql: all admin tables + RLS policies ready", "NONE", "no tests", "NO — 0% built", "Supabase", "weeks", "YES (DB ready)"],
  ["Promoter Dashboard", "LEAD-CAPTURE: \"success screen: personal ?ref= link + share intents + queue position\"; index.html: \"How a promoter earns\" 4-step flow", "0001_core.sql: tasks, payouts, disputes, profiles with trust_score", "NONE (only lead capture form)", "no tests", "NO — 0% built", "Supabase", "weeks", "YES (DB ready)"],
  ["Business / Campaign Manager", "README: \"businesses fund campaigns\"; index.html: \"Pay for outcomes you can count\" + pilot terms", "0001_core.sql: campaigns, escrow funding, auto-pause, margin floor", "NONE", "no tests", "NO — 0% built", "Supabase + payment gateway", "weeks", "NO (needs payment gateway)"],
  ["Partner Portal", "README: \"Partners\" section; index.html: agencies, data resellers, communities", "0001_core.sql: partner role + permissions", "NONE", "no tests", "NO — 0% built", "Supabase", "weeks", "YES (DB ready)"],
  ["Fraud Detection / Trust Scoring", "BRAND: \"filters for automated clicks, a trust score, human review of a sample, payout holds, and clawback\"; STATUS: \"fraud.hold_threshold, fraud.ban_threshold, fraud.review_sample_pct\" settings", "0001_core.sql: profiles.trust_score; settings: fraud.hold_threshold, fraud.ban_threshold, fraud.review_sample_pct, fraud.reserve_bp; tasks: proof_url, hold_until, reviewed_by,rejection_reason; disputes", "server.mjs: NONE; apps/web/app.js: NONE", "ledger.test.mjs: fraud reserve + margin floor proven at campaign level; no trust score computation tests", "NO — no fraud worker, no trust score algorithm", "ML/fraud detection service or custom rules engine", "weeks (fraud worker + scoring + review queue)", "YES (can build rules-based first)"],
  ["Data Aggregator Integration", "BRAND: \"MTN, Glo and Airtel at pilot, sent through a licensed aggregator rather than direct carrier integration. 9mobile is planned.\"", "payouts.kind=data + DATA_PAYABLE_NGN account; settings: payout.min_data_minor", "NONE", "no tests", "NO — no integration", "Data aggregator (Termii, Migo, Arkesel, etc.)", "weeks (aggregator API + webhook + reconciliation)", "NO (requires aggregator)"],
  ["Compliance / Regulatory", "BRAND: \"No joining fee. No payment for recruiting. No income promises. Ever.\"; LEAD-CAPTURE: \"anti-MLM rule... referrals pay ZERO\"; STATUS: \"Trademark + CAC + domain clearance... UNVERIFIED\"; \"Registered entity name/jurisdiction + PII-storage decision\" blocker", "0001_core.sql: audit_log; profiles.date_of_birth_hmac (never raw DOB); identity_ref (provider token OR HMAC); leads: consent_at timestamp (NDPA s.27)", "NONE", "no tests", "NO — legal entity + trademark + CAC + domain + NDPA compliance + SEC compliance", "Legal counsel (Nigerian corporate + fintech + data protection)", "weeks-months", "NO (requires legal counsel)"],
];

function escapeCsv(field) {
  if (field.includes('"') || field.includes(',') || field.includes('\n')) {
    return '"' + field.replace(/"/g, '""') + '"';
  }
  return field;
}

const csv = rows.map(row => row.map(escapeCsv).join(',')).join('\n');
fs.writeFileSync('C:\\Users\\pc\\owoworks\\audit\\full-gap-matrix.csv', csv, 'utf8');
console.log('CSV written successfully');
