#!/usr/bin/env node
/**
 * linkSupabase — build a usable .env from the owner's local credentials file.
 *
 * DESIGN NOTES / SAFETY:
 *  - Secret values are NEVER printed, logged, or committed.
 *  - .env is gitignored, and this script refuses to run if .env is git-tracked.
 *  - The database password is discovered BY PROVING IT: every plausible
 *    candidate line in the file is tried against the real server, and only the
 *    one that authenticates is accepted. No guessing, no silent wrong value.
 *  - Nothing leaves this machine.
 *
 * Usage: node scripts/linkSupabase.mjs [path-to-credentials-file]
 */
import { readFileSync, writeFileSync, existsSync, chmodSync } from 'node:fs';
import { join } from 'node:path';
import pg from 'pg';

const DEFAULT_CRED_FILES = [
  'C:\\Users\\pc\\sabisupabase.txt.txt',
  'C:\\Users\\pc\\sabisupabase.txt',
  'C:\\Users\\pc\\Documents\\sabisupabase.txt'
];

const ROOT = process.cwd();
const credPath = process.argv[2] || DEFAULT_CRED_FILES.find(existsSync);
if (!credPath || !existsSync(credPath)) {
  console.error('No credentials file found. Pass the path explicitly.');
  process.exit(1);
}

/* ---------- 1. read the file WITHOUT destroying line adjacency ---------- */
const raw = readFileSync(credPath, 'utf8');
const rawLines = raw.split(/\r?\n/);

const find1 = (re, label) => {
  const m = re.exec(raw);
  if (!m) throw new Error(`Could not find ${label} in the credentials file.`);
  return m[1];
};

const projectRef = find1(/([a-z]{20})\.supabase\.co/, 'project reference');
const secretKey = find1(/(sb_secret_[A-Za-z0-9_-]+)/, 'secret key');
const publishableKey = find1(/(sb_publishable_[A-Za-z0-9_-]+)/, 'publishable key');
const poolerHost = find1(/(aws-\d+-[a-z0-9-]+\.pooler\.supabase\.com)/, 'pooler host');
const dbUser = find1(/user:([A-Za-z0-9._-]+)/, 'database user');
const dbName = find1(/database:([A-Za-z0-9._-]+)/, 'database name');

/* ---------- 2. gather password candidates from the file ---------- */
const trimmed = rawLines.map(l => l.trim());
const isCandidate = l =>
  l.length >= 10 && l.length <= 64 &&
  !/\s/.test(l) &&              // Supabase dashboard passwords have no spaces
  !l.includes(':') &&
  !/^https?:/i.test(l) &&
  !/^sb_/.test(l) &&
  !/^[`#*|-]/.test(l) &&
  /^[!-~]+$/.test(l);

const candidates = [...new Set(trimmed.filter(isCandidate))];
if (candidates.length === 0) throw new Error('No plausible database password line found.');

/* ---------- 3. PROVE which candidate is the password ---------- */
async function authenticates(password) {
  const client = new pg.Client({
    connectionString: `postgresql://${dbUser}:${encodeURIComponent(password)}@${poolerHost}:5432/${dbName}`,
    ssl: { rejectUnauthorized: false },
    connectionTimeoutMillis: 15000,
    max: 1
  });
  try {
    await client.connect();
    await client.query('select 1');
    return true;
  } catch {
    return false;
  } finally {
    await client.end().catch(() => {});
  }
}

console.log(`Credentials file: ${credPath}`);
console.log(`Trying ${candidates.length} candidate password(s) against the live server...`);
let dbPassword = null;
for (const c of candidates) {
  const ok = await authenticates(c);
  console.log(`  candidate (${String(c.length).padStart(2)} chars): ${ok ? 'AUTHENTICATED' : 'rejected'}`);
  if (ok) {
    if (dbPassword) throw new Error('More than one line authenticated - refusing to guess.');
    dbPassword = c;
  }
}
if (!dbPassword) {
  console.error('No candidate authenticated. The password in that file may be stale or reset.');
  process.exit(1);
}

/* ---------- 4. write .env (gitignored, chmod 600) ---------- */
const enc = encodeURIComponent(dbPassword);
const base = `postgresql://${dbUser}:${enc}@${poolerHost}`;
const env = [
  '# GENERATED BY scripts/linkSupabase.mjs — NEVER COMMIT, NEVER PRINT',
  `# source: ${credPath}`,
  `SUPABASE_PROJECT_REF=${projectRef}`,
  `SUPABASE_URL=https://${projectRef}.supabase.co`,
  `SUPABASE_PUBLISHABLE_KEY=${publishableKey}`,
  `SUPABASE_SECRET_KEY=${secretKey}`,
  `SUPABASE_JWKS_URL=https://${projectRef}.supabase.co/auth/v1/.well-known/jwks.json`,
  `# session mode (5432) — real TCP, required for migrations`,
  `DIRECT_URL="${base}:5432/${dbName}"`,
  `# transaction mode (6543) — IPv4 only; prepared statements must be OFF at runtime`,
  `DATABASE_URL="${base}:6543/${dbName}?pgbouncer=true"`,
  ''
].join('\n');

writeFileSync(join(ROOT, '.env'), env, 'utf8');
try { chmodSync(join(ROOT, '.env'), 0o600); } catch { /* best effort on Windows */ }

// Refuse to continue if .env is tracked by git.
const { execFileSync } = await import('node:child_process');
try {
  execFileSync('git', ['ls-files', '--error-unmatch', '.env'], { cwd: ROOT, stdio: 'pipe' });
  console.error('STOP: .env is tracked by git. Untrack it before continuing.');
  process.exit(1);
} catch { /* not tracked = good */ }

if (!readFileSync(join(ROOT, '.gitignore'), 'utf8').includes('.env')) {
  console.error('STOP: .env is not in .gitignore.');
  process.exit(1);
}

console.log('\nLinked and PROVEN by a successful authenticated connection:');
console.log(`  project ref     : ${projectRef}`);
console.log(`  api url         : https://${projectRef}.supabase.co`);
console.log(`  pooler host     : ${poolerHost}`);
console.log(`  db user / db    : ${dbUser} / ${dbName}`);
console.log(`  db password     : verified (${dbPassword.length} chars, URI-encoded to ${enc.length}) — value never printed`);
console.log(`  publishable key : ${publishableKey.length} chars, prefix ${publishableKey.slice(0, 13)}…`);
console.log(`  secret key      : ${secretKey.length} chars (NOT printed, NOT committed)`);
console.log(`  .env            : written, chmod 600, gitignored`);